title: 我的个人博客
description: 记录我的技术学习和生活点滴
baseurl: "" # 子路径，如果博客在子目录下使用
url: "https://telegeni.site" # 你的网站地址

# 构建设置
markdown: kramdown
permalink: pretty

# 主题设置
theme: jekyll-theme-chirpy

# 插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# 分页设置
paginate: 5
paginate_path: "/page:num/"

# 归档设置
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# 评论系统 (可选)
comments:
  provider: giscus
  giscus:
    repo: tele-geni/tele-geni.github.io
    repo-id: YOUR_REPO_ID
    category: General
    category-id: YOUR_CATEGORY_ID
    mapping: pathname
    reactions-enabled: 1
    emit-metadata: 0
    theme: light

# 搜索设置
search: true

# 社交链接
social:
  github: tele-geni
  email: your-email@example.com

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore 